# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft Properties

parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05
minecraft_version=1.21.9
minecraft_version_range=[1.21.9,1.22)
neo_version=21.9.16-beta

# Mod Properties

mod_id=storagedelight
mod_name=Storage Delight
mod_license=MIT
mod_version=25.12.03-1.21.9-neoforge
mod_group_id=com.axperty.storagedelight
mod_authors=Axperty
mod_description=A mod that adds more storage options to the game.