org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_id=storagedelight
mod_name=Storage Delight
mod_license=MIT
mod_version=26.07.01-1.21-fabric
mod_authors=Axperty
mod_description=A mod that adds more storage options to the game.
maven_group=com.axperty
archives_base_name=storagedelight

# Dependencies
fabric_api_version=0.116.11+1.21.1