org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=storagedelight
mod_name=Storage Delight
mod_license=MIT
mod_version=26.07.01-26.2-fabric
mod_authors=Axperty
mod_description=A mod that adds more storage options to the game.
maven_group=com.axperty
archives_base_name=storagedelight

# Dependencies
fabric_api_version=0.152.2+26.2